export interface CareerPathItem {
  id: string;
  title: string;
  category: 'Software & Data' | 'Systems & Hardware' | 'Core & Infrastructure' | 'Exams & Higher Ed';
  badge: string;
  description: string;
  requiredSkills: string[];
  typicalRoles: string[];
  avgSalary: string;
  roadmapSlug?: string;
  roadmapUrl?: string;
  demandLevel: 'Very High' | 'High' | 'Steady';
}

export const CAREER_PATHS: CareerPathItem[] = [
  {
    id: 'software-dev',
    title: 'Software Development',
    category: 'Software & Data',
    badge: 'High Placement Volume',
    description: 'Build scalable backend services, microservices, algorithms, and core enterprise software systems with high algorithmic efficiency.',
    requiredSkills: ['Data Structures & Algorithms', 'C++ / Java', 'System Design', 'SQL / NoSQL', 'Git & Linux'],
    typicalRoles: ['Software Engineer', 'Backend Developer', 'Systems Engineer', 'Application Architect'],
    avgSalary: '₹8 - 24 LPA',
    roadmapSlug: 'full-stack-software-engineer-roadmap-2025',
    demandLevel: 'Very High',
  },
  {
    id: 'full-stack',
    title: 'Full Stack Development',
    category: 'Software & Data',
    badge: 'Most Popular',
    description: 'Master end-to-end web architectures from responsive React/Next.js frontends to high-throughput Node.js/Go APIs and cloud databases.',
    requiredSkills: ['React 19 / Next.js', 'Node.js / Express', 'TypeScript', 'PostgreSQL / MongoDB', 'Docker & REST/GraphQL'],
    typicalRoles: ['Full Stack Engineer', 'Frontend Engineer', 'MERN / Next.js Specialist', 'Tech Lead'],
    avgSalary: '₹7 - 22 LPA',
    roadmapSlug: 'full-stack-software-engineer-roadmap-2025',
    demandLevel: 'Very High',
  },
  {
    id: 'ai-ml',
    title: 'AI & Machine Learning',
    category: 'Software & Data',
    badge: 'Trending & Fast Growing',
    description: 'Design deep learning architectures, LLM integrations, computer vision pipelines, and production machine learning models.',
    requiredSkills: ['Python & PyTorch / TensorFlow', 'Linear Algebra & Calculus', 'Scikit-Learn', 'LLMs & LangChain', 'MLOps & FastAPI'],
    typicalRoles: ['AI/ML Engineer', 'Computer Vision Engineer', 'NLP Specialist', 'Applied AI Researcher'],
    avgSalary: '₹10 - 28 LPA',
    demandLevel: 'Very High',
  },
  {
    id: 'data-science',
    title: 'Data Science & Analytics',
    category: 'Software & Data',
    badge: 'High Business Impact',
    description: 'Extract statistical insights, build predictive pipelines, optimize decision models, and design executive business intelligence dashboards.',
    requiredSkills: ['Python / R', 'SQL & Data Warehousing', 'Pandas & NumPy', 'Tableau / PowerBI', 'Statistical Inference'],
    typicalRoles: ['Data Scientist', 'Data Analyst', 'BI Engineer', 'Quantitative Analyst'],
    avgSalary: '₹7 - 20 LPA',
    demandLevel: 'High',
  },
  {
    id: 'cloud-devops',
    title: 'Cloud & DevOps Engineering',
    category: 'Software & Data',
    badge: 'Crucial Infrastructure',
    description: 'Automate deployment pipelines, orchestrate Kubernetes clusters, and architect zero-downtime, multi-region cloud infrastructures.',
    requiredSkills: ['AWS / Azure / GCP', 'Docker & Kubernetes', 'CI/CD (GitHub Actions)', 'Terraform (IaC)', 'Linux & Bash'],
    typicalRoles: ['DevOps Engineer', 'Cloud Architect', 'Site Reliability Engineer (SRE)', 'Platform Engineer'],
    avgSalary: '₹9 - 25 LPA',
    demandLevel: 'Very High',
  },
  {
    id: 'cybersecurity',
    title: 'Cybersecurity & InfoSec',
    category: 'Software & Data',
    badge: 'High Security Demand',
    description: 'Protect enterprise infrastructure, perform vulnerability assessments, ethical hacking, secure code audits, and incident response.',
    requiredSkills: ['Network Security & Protocols', 'Ethical Hacking & Burp Suite', 'Cryptography', 'SIEM & SOC Operations', 'Linux Internals'],
    typicalRoles: ['Security Analyst', 'Penetration Tester', 'SOC Analyst', 'Application Security Engineer'],
    avgSalary: '₹8 - 22 LPA',
    demandLevel: 'High',
  },
  {
    id: 'core-mech',
    title: 'Core Mechanical Engineering',
    category: 'Core & Infrastructure',
    badge: 'Industrial Manufacturing & R&D',
    description: 'Specialize in CAD/CAM 3D modeling, FEA simulation, thermal systems, automotive engineering, and automated production machinery.',
    requiredSkills: ['AutoCAD / SolidWorks / CATIA', 'ANSYS & FEA Simulation', 'Thermodynamics & Fluid Dynamics', 'GD&T Standards', 'CNC & Manufacturing Processes'],
    typicalRoles: ['Mechanical Design Engineer', 'R&D Engineer', 'Thermal Systems Analyst', 'Production Manager'],
    avgSalary: '₹5.5 - 15 LPA',
    demandLevel: 'Steady',
  },
  {
    id: 'electrical-eng',
    title: 'Electrical Engineering & Power',
    category: 'Core & Infrastructure',
    badge: 'EV & Renewable Energy Hub',
    description: 'Lead power system distribution, switchgear design, electric vehicle (EV) battery packs, inverters, and industrial automation.',
    requiredSkills: ['MATLAB / Simulink', 'Power Electronics', 'PLC & SCADA Automation', 'High Voltage Systems', 'EV Powertrain & BMS'],
    typicalRoles: ['Power Systems Engineer', 'Electrical Design Engineer', 'EV Battery Specialist', 'Automation Engineer'],
    avgSalary: '₹6 - 16 LPA',
    demandLevel: 'High',
  },
  {
    id: 'embedded-systems',
    title: 'Electronics & Embedded Systems',
    category: 'Systems & Hardware',
    badge: 'Semiconductor & IoT Boom',
    description: 'Program microcontrollers, firmware, VLSI circuits, ARM Cortex boards, and IoT edge hardware for consumer and automotive tech.',
    requiredSkills: ['Embedded C / C++', 'Microcontrollers (STM32/ESP32)', 'RTOS & Kernel Drivers', 'UART/SPI/I2C Protocols', 'VLSI & Verilog'],
    typicalRoles: ['Firmware Engineer', 'Embedded Systems Developer', 'IoT Hardware Engineer', 'VLSI Design Engineer'],
    avgSalary: '₹7 - 20 LPA',
    demandLevel: 'High',
  },
  {
    id: 'civil-eng',
    title: 'Civil & Structural Engineering',
    category: 'Core & Infrastructure',
    badge: 'Smart Infrastructure & Urban',
    description: 'Design earthquake-resistant structures, BIM 3D architectural modeling, transportation networks, and sustainable smart cities.',
    requiredSkills: ['STAAD Pro / ETABS', 'AutoCAD & Revit BIM', 'Structural Analysis', 'Geotechnical Engineering', 'Project Estimation & Scheduling'],
    typicalRoles: ['Structural Engineer', 'BIM Modeler', 'Site Execution Engineer', 'Urban Infrastructure Planner'],
    avgSalary: '₹5 - 14 LPA',
    demandLevel: 'Steady',
  },
  {
    id: 'gate-govt',
    title: 'GATE & Government PSU Careers',
    category: 'Exams & Higher Ed',
    badge: 'Prestigious & High Job Security',
    description: 'Crack GATE with top AIR for direct officer-level recruitment in Maharatna PSUs (IOCL, ONGC, NTPC, BARC, ISRO) and top IIT M.Tech seats.',
    requiredSkills: ['Subject Theoretical Mastery', 'Engineering Mathematics & Aptitude', 'Numerical Speed & Accuracy', 'Previous 25-Year PYQs Analysis'],
    typicalRoles: ['PSU Executive Engineer', 'ISRO/DRDO Scientist \'SC\'', 'IES Officer', 'IIT Research Scholar'],
    avgSalary: '₹14 - 22 LPA (CTC + Perks)',
    roadmapSlug: 'gate-cs-it-complete-preparation-strategy',
    demandLevel: 'Very High',
  },
  {
    id: 'higher-studies',
    title: 'Higher Studies / M.Tech / MS Abroad',
    category: 'Exams & Higher Ed',
    badge: 'Global Research & Specialization',
    description: 'Pursue specialized M.Tech at IISc/IITs or MS in Computer Science, Robotics, Data Science at top global universities in USA, Germany & Europe.',
    requiredSkills: ['GRE & TOEFL/IELTS Prep', 'Research Papers & Capstone Projects', 'SOP & Academic LORs', 'Domain Specialization Prep'],
    typicalRoles: ['Research Scientist', 'Global Tech Specialist', 'PhD Fellow', 'University Faculty'],
    avgSalary: '$90k - $140k / ₹25+ LPA',
    demandLevel: 'High',
  },
];

export const WHY_COUNSELLING_FEATURES = [
  {
    icon: 'Compass',
    title: 'Discover Your Strengths',
    description: 'Identify your natural technical aptitude, mathematical affinity, coding appetite, and areas for improvement with our structured diagnostic framework.',
    color: 'blue',
  },
  {
    icon: 'Layers',
    title: 'Choose the Right Career',
    description: 'Clear comparative insights between Software Development, AI/ML, Cloud, Core Engineering, GATE PSUs, and Higher Studies based on current market hiring trends.',
    color: 'indigo',
  },
  {
    icon: 'Map',
    title: 'Build a Personalized Roadmap',
    description: 'Get a semester-by-semester milestone plan tailored to your university branch, remaining academic semesters, and target dream package.',
    color: 'cyan',
  },
  {
    icon: 'Target',
    title: 'Identify Skill Gaps',
    description: 'Pinpoint exactly which technical libraries, system design concepts, and real-world projects you are missing compared to top selected candidates.',
    color: 'amber',
  },
  {
    icon: 'Users',
    title: 'Get Ex-IITian Expert Guidance',
    description: 'Speak 1-on-1 with senior faculty and industry veterans who have mentored over 15,000+ engineering graduates and evaluated university curricula.',
    color: 'emerald',
  },
  {
    icon: 'Briefcase',
    title: 'Plan Your Placement Strategy',
    description: 'Align your preparation timeline for on-campus drives, off-campus hiring, resume ATS optimization, and technical mock interview rounds.',
    color: 'purple',
  },
];

export const HOW_IT_WORKS_STEPS = [
  {
    stepNumber: '01',
    title: 'Tell Us About Yourself',
    subtitle: 'Profile & Background Intake',
    description: 'Share your engineering branch, semester, current technical knowledge, interests, academic CGPA, and dream career aspiration.',
    deliverable: 'Diagnostic Profile Record',
    icon: 'UserCheck',
  },
  {
    stepNumber: '02',
    title: 'In-Depth Career Assessment',
    subtitle: 'Diagnostic Evaluation',
    description: 'Our diagnostic evaluation assesses your problem-solving style, coding affinity, hardware vs software orientation, and exam readiness.',
    deliverable: 'Fitment Scorecard',
    icon: 'Brain',
  },
  {
    stepNumber: '03',
    title: 'Personalized Guidance & Plan',
    subtitle: 'Customized Recommendations',
    description: 'Receive recommended career paths, high-yield skill checklist, semester milestone timeline, and project recommendations.',
    deliverable: 'Custom Engineering Action Plan',
    icon: 'FileText',
  },
  {
    stepNumber: '04',
    title: 'Take Action with Expert Mentorship',
    subtitle: 'Execution & Continuous Support',
    description: 'Access curated notes, roadmaps, recommended free tools, and 1-on-1 sessions at our Pune center or online to achieve your target role.',
    deliverable: '1-on-1 Mentorship & Drives',
    icon: 'Rocket',
  },
];

export const STUDENT_STAGES = [
  {
    stageId: 'fe',
    badge: '1st Year (FE)',
    title: 'First-Year Engineering Students',
    tagline: 'Build Strong Engineering Fundamentals',
    focus: 'Master Engineering Mathematics, basic C/Python programming, core engineering mechanics, and overcome 11th/12th conceptual gaps.',
    milestones: ['Clear all M-I & M-II fundamentals', 'Learn C/C++ or Python from scratch', 'Explore different branch trajectories early', 'Maintain 8.5+ First Year CGPA'],
    ctaText: 'Get 1st Year Guidance',
    accentColor: 'blue',
  },
  {
    stageId: 'se',
    badge: '2nd Year (SE)',
    title: 'Second-Year Engineering Students',
    tagline: 'Choose Specialization & Build Projects',
    focus: 'Commit to a core technical domain (Web, AI, Cloud, Core Design), master Data Structures & Algorithms, and build initial portfolio projects.',
    milestones: ['Complete 100+ DSA problems', 'Build 2 full-stack or core simulation projects', 'Learn Git, Linux, and databases (SQL)', 'Identify target tier of companies / GATE'],
    ctaText: 'Get 2nd Year Roadmap',
    accentColor: 'indigo',
  },
  {
    stageId: 'te',
    badge: '3rd Year (TE)',
    title: 'Third-Year Engineering Students',
    tagline: 'Internships & Competitive Exam Prep',
    focus: 'Aggressively prepare for summer internships, master system design/core subjects, start serious GATE 12-month study, and build production apps.',
    milestones: ['Secure paid summer internship', 'Advanced DSA + System Design / GATE syllabus', 'Publish technical capstone on GitHub', 'Craft ATS-compliant tech resume'],
    ctaText: 'Get 3rd Year Placement Plan',
    accentColor: 'amber',
  },
  {
    stageId: 'be',
    badge: 'Final Year (BE)',
    title: 'Final-Year & Recent Graduates',
    tagline: 'On-Campus, Off-Campus & Interview Sprints',
    focus: 'Mock technical interviews, off-campus drive referrals, behavioral preparation, salary negotiation, or final GATE AIR booster mock series.',
    milestones: ['Target 20+ verified off-campus drives', 'Daily mock coding & technical interviews', 'Final year capstone optimization', 'Finalize multiple job offers / M.Tech seat'],
    ctaText: 'Get Placement Acceleration',
    accentColor: 'emerald',
  },
  {
    stageId: 'working',
    badge: 'Working Professionals',
    title: 'Working Engineers & Career Switchers',
    tagline: 'Upskilling, Service-to-Product & Salary Multiplier',
    focus: 'Strategic transition from legacy service companies / non-tech roles to product-based SDE, AI/ML engineer, cloud architect, or Executive M.Tech.',
    milestones: ['High-level & Low-level System Design', 'Transition to Modern Cloud / AI tech stacks', 'Weekend flexible mentorship', 'Target 2x - 3x CTC hikes in top firms'],
    ctaText: 'Get Career Switch Roadmap',
    accentColor: 'purple',
  },
];

export interface ComparisonRow {
  feature: string;
  apexValue: string;
  apexStatus: 'free' | 'available' | 'included' | 'personalized' | 'specialized';
  paidValue: string;
  paidStatus: 'paid' | 'expensive' | 'limited';
  govtValue: string;
  govtStatus: 'limited' | 'not-available' | 'basic';
  tooltip?: string;
}

export const COMPARISON_TABLE_DATA: ComparisonRow[] = [
  {
    feature: 'Expert 1-on-1 Guidance Session',
    apexValue: '✓ Free 1-on-1 Session',
    apexStatus: 'free',
    paidValue: '₹2,500 – ₹5,000 / Hour',
    paidStatus: 'expensive',
    govtValue: '✕ Not Available (Group Only)',
    govtStatus: 'not-available',
    tooltip: 'Direct face-to-face or online session with senior Ex-IITian faculty.',
  },
  {
    feature: 'AI Career Fitment & Profile Assessment',
    apexValue: '✓ Free Instant Analysis',
    apexStatus: 'free',
    paidValue: '₹1,500 – ₹3,000 or Paywalled',
    paidStatus: 'paid',
    govtValue: 'Basic Generic Aptitude Test',
    govtStatus: 'basic',
    tooltip: 'Detailed multi-branch scoring comparing coding, math, hardware, and research aptitude.',
  },
  {
    feature: 'Personalized College & Specialization List',
    apexValue: '✓ Free Tailored List',
    apexStatus: 'free',
    paidValue: '₹5,000 – ₹15,000 Packages',
    paidStatus: 'expensive',
    govtValue: 'Standard Cutoff PDFs Only',
    govtStatus: 'basic',
    tooltip: 'Curated list based on your CET/JEE score, home university, and preferred branch.',
  },
  {
    feature: 'Direct WhatsApp & Counselor Desk',
    apexValue: '✓ Free Dedicated Desk',
    apexStatus: 'free',
    paidValue: 'Ticket-based (24-48 hr delay)',
    paidStatus: 'limited',
    govtValue: '✕ No WhatsApp Support',
    govtStatus: 'not-available',
    tooltip: 'Quick answers for admission, syllabus, and career roadmaps.',
  },
  {
    feature: 'Follow-up Mentorship Sessions',
    apexValue: '✓ Free & Readily Available',
    apexStatus: 'available',
    paidValue: 'Billed per follow-up call',
    paidStatus: 'expensive',
    govtValue: '✕ No Follow-up Support',
    govtStatus: 'not-available',
    tooltip: 'Regular milestone check-ins throughout your semester.',
  },
  {
    feature: 'Working Professional Transition Guidance',
    apexValue: '✓ Available & Flexible',
    apexStatus: 'available',
    paidValue: '₹25,000+ Executive Track',
    paidStatus: 'expensive',
    govtValue: '✕ Current Students Only',
    govtStatus: 'not-available',
    tooltip: 'Guidance on switching from service to product companies.',
  },
  {
    feature: 'Engineering College & Branch Database',
    apexValue: '✓ Free & Fully Searchable',
    apexStatus: 'free',
    paidValue: 'Subscription Locked',
    paidStatus: 'paid',
    govtValue: 'Static State Web Portals',
    govtStatus: 'basic',
    tooltip: 'Historical placement records, cutoffs, and faculty details.',
  },
  {
    feature: 'GATE / PSU / Higher Studies Guidance',
    apexValue: '✓ Specialized Ex-IITian Mentors',
    apexStatus: 'specialized',
    paidValue: 'Separate Coaching (₹40,000+)',
    paidStatus: 'expensive',
    govtValue: 'General Syllabus Info Only',
    govtStatus: 'basic',
    tooltip: 'Unit weightage breakdowns, standard book recommendations, and rank strategy.',
  },
  {
    feature: 'Semester-by-Semester Career Roadmap',
    apexValue: '✓ Personalized & Actionable',
    apexStatus: 'personalized',
    paidValue: 'Generic Static PDF Templates',
    paidStatus: 'limited',
    govtValue: '✕ Not Available',
    govtStatus: 'not-available',
    tooltip: 'Tailored milestone timeline matching your exact university semester.',
  },
  {
    feature: 'Technical Skill Gap Analysis',
    apexValue: '✓ Included with Tech Audit',
    apexStatus: 'included',
    paidValue: 'Paid Premium Assessment',
    paidStatus: 'paid',
    govtValue: '✕ Not Available',
    govtStatus: 'not-available',
    tooltip: 'Detailed audit comparing your skills with active JD requirements.',
  },
  {
    feature: 'Placement & Company Drive Guidance',
    apexValue: '✓ Included with Referral Alerts',
    apexStatus: 'included',
    paidValue: '₹30,000+ Placement Packages',
    paidStatus: 'expensive',
    govtValue: '✕ Notice Boards Only',
    govtStatus: 'not-available',
    tooltip: 'Direct guidance on applying to verified active engineering drives.',
  },
  {
    feature: 'Internship Strategy & Project Selection',
    apexValue: '✓ Included with Code Reviews',
    apexStatus: 'included',
    paidValue: 'Paid Add-on Service',
    paidStatus: 'paid',
    govtValue: 'Limited National Portals',
    govtStatus: 'basic',
    tooltip: 'Tips on selecting unique resume-worthy capstone projects.',
  },
  {
    feature: 'ATS Resume Review & Feedback',
    apexValue: '✓ Available at Pune Center / Online',
    apexStatus: 'available',
    paidValue: '₹1,500 – ₹3,500 Per Review',
    paidStatus: 'paid',
    govtValue: '✕ Not Available',
    govtStatus: 'not-available',
    tooltip: 'Human + ATS check to ensure your resume passes screening filters.',
  },
  {
    feature: 'Technical Mock Interview Guidance',
    apexValue: '✓ Available with Industry Faculty',
    apexStatus: 'available',
    paidValue: '₹3,000 – ₹7,000 Per Mock',
    paidStatus: 'expensive',
    govtValue: '✕ Not Available',
    govtStatus: 'not-available',
    tooltip: 'Realistic mock rounds with real-time feedback on DSA and system design.',
  },
];

export const FAQS_DATA = [
  {
    question: 'What is engineering career counselling at Apex Engineering Academy?',
    answer: 'Engineering career counselling is a personalized, diagnostic guidance session where our senior academic and industry mentors analyze your academic standing, engineering branch, current technical skills, coding aptitude, and career ambitions. We help you choose the right specialization (e.g. Full Stack, AI/ML, Cloud, Core Mechanical/Electrical, GATE, or Higher Studies) and construct an actionable, semester-by-semester learning and project roadmap.',
  },
  {
    question: 'Is career counselling really 100% free at Apex?',
    answer: 'Yes, our 1-on-1 career counselling sessions, AI profile assessment, and engineering roadmap consultations are 100% free with zero obligation. As an educational academy with an offline center in Pune, our mission is to ensure every engineering student has clarity on their trajectory before investing time and money.',
  },
  {
    question: 'Who can use Apex career counselling?',
    answer: 'Our career counselling is designed for: (1) 1st to 4th-year engineering students across all branches (CSE, IT, AI&DS, E&TC, Mechanical, Civil), (2) Diploma to Degree students, (3) Recent engineering graduates preparing for off-campus placement drives, (4) GATE and PSU aspirants, and (5) Working professionals seeking a strategic switch to product companies or high-growth tech domains.',
  },
  {
    question: 'Can I get guidance specifically for software engineering roles?',
    answer: 'Absolutely. We provide deep technical guidance on mastering Data Structures & Algorithms, competitive coding, modern frontend/backend stacks (React 19, Next.js, Node.js, Go), system design fundamentals, database internals, and strategies to clear coding rounds in product companies (Tier-1 & Tier-2).',
  },
  {
    question: 'Can you help with AI and Machine Learning careers?',
    answer: 'Yes! We guide you through the real-world mathematical prerequisites (Linear Algebra, Multivariate Calculus, Probability), Python data science ecosystems (NumPy, Pandas, PyTorch), LLM application engineering, and MLOps deployment workflows required to stand out from generic tutorial builders.',
  },
  {
    question: 'Can you guide me for GATE & PSU engineering exams?',
    answer: 'Yes. Our chief mentors include Ex-IITians and GATE top rankers who break down subject-wise weightage, standard reference textbooks, 12-month preparation timelines, and previous 25-year question solving techniques for cracking PSU interviews (IOCL, ONGC, NTPC, BARC) or securing M.Tech admissions at IIT Bombay/IISc.',
  },
  {
    question: 'Can working professionals use the counselling service?',
    answer: 'Yes. We frequently counsel working engineers stuck in legacy maintenance projects or service companies. We outline custom upskilling paths in Cloud/DevOps, Full Stack, or AI, and provide guidance on resume repositioning and compensation negotiation.',
  },
  {
    question: 'Can I get a personalized semester-by-semester career roadmap?',
    answer: 'Yes. Following your diagnostic intake or 1-on-1 session, our mentors provide a structured roadmap detailing which technical skills, projects, and certifications you should target in each semester of your degree.',
  },
  {
    question: 'How does the interactive AI career assessment work?',
    answer: 'Our interactive assessment takes your branch, current year, mathematical affinity, coding interest, hardware inclination, and career goals to compute a multi-dimensional fitment percentage across top engineering paths. It instantly highlights your best-fit careers, skill gap checklist, and recommended roadmaps.',
  },
  {
    question: 'Can I speak directly with a career expert in person at the Pune center?',
    answer: 'Yes! You can choose to meet our senior faculty in person at our flagship learning center at FC Road / Deccan Gymkhana, Pune, or schedule a 1-on-1 Google Meet / WhatsApp session from anywhere in India.',
  },
];
