export const DEFAULT_JOBS = [
  {
    _id: 'amazon-ml-2026',
    title: 'Associate, ML Data Operations',
    slug: 'amazon-associate-ml-data-operations-2026',
    companyName: 'Amazon',
    jobType: 'OFF_CAMPUS',
    location: 'Hyderabad / Chennai / Pune / Hybrid',
    workMode: 'HYBRID',
    salaryOrStipend: '₹4.5 - 7.5 LPA',
    salaryRange: '₹4.5 - 7.5 LPA',
    batchEligible: ['2024', '2025', '2026', 'Freshers & Experienced'],
    eligibility: 'Freshers & Experienced (All Engineering Batches 2024, 2025, 2026)',
    applicationDeadline: '2026-12-31',
    deadline: '2026-12-31',
    applyUrl: 'https://www.amazon.jobs/en/jobs/3134249/associate-ml-data-operations-go-ai-operations?utm_source=chatgpt.com',
    whatsappCommunityUrl: 'https://whatsapp.com/channel/0029VbDKVvNHrDZgmPJIav3O',
    description: `Amazon is hiring for the Associate, ML Data Operations role. This is a great opportunity for candidates interested in Machine Learning, Data Operations, AI and technology.

🔹 Work with machine-learning related data operations
🔹 Support data quality and annotation processes
🔹 Work with operational and technical teams
🔹 Opportunity to gain experience in a global technology company`,
    requirements: [
      'Basic understanding of Machine Learning and AI data operations',
      'Strong analytical and data annotation / quality auditing skills',
      'Effective verbal and written communication skills',
      'Proficiency in MS Excel / Google Sheets and basic computer operations',
      'Ability to work in a collaborative and fast-paced environment',
    ],
    selectionRounds: ['Online Assessment', 'Technical & Data Aptitude Test', 'HR / Operations Interview'],
    tags: ['Amazon', 'OffCampus', 'MLOps', 'Freshers2026', 'AIJobs'],
    status: 'PUBLISHED',
    publishedAt: new Date().toISOString(),
    viewCount: 1420,
    clickCount: 385,
    applicantsCount: 385,
  },
  {
    _id: 'nvidia-sde-1',
    title: 'Graduate Software Development Engineer (SDE-1)',
    slug: 'nvidia-graduate-sde-1-pune',
    companyName: 'NVIDIA',
    jobType: 'FULL_TIME',
    location: 'Pune / Bengaluru',
    workMode: 'HYBRID',
    salaryOrStipend: '₹16 - 24 LPA',
    salaryRange: '₹16 - 24 LPA',
    batchEligible: ['2025', '2026'],
    eligibility: 'B.E. / B.Tech in CSE, IT, E&TC (Min 7.5 CGPA)',
    applicationDeadline: '2026-11-30',
    deadline: '2026-11-30',
    applyUrl: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite',
    whatsappCommunityUrl: 'https://whatsapp.com/channel/0029VbDKVvNHrDZgmPJIav3O',
    description: 'Design and optimize core GPU acceleration software, CUDA runtime libraries, and distributed deep learning infrastructure for next-generation AI platforms.',
    requirements: [
      'Strong proficiency in Modern C++ (17/20) and Data Structures & Algorithms',
      'Understanding of Computer Architecture, OS Internals, and Multi-threading',
      'Experience with Linux development and debugging tools (GDB, Valgrind)',
    ],
    selectionRounds: ['Coding Round (DSA)', 'Core CS Fundamentals (OS/CN/Architecture)', 'System Design', 'Managerial'],
    tags: ['NVIDIA', 'C++', 'CUDA', 'Systems', 'HighCTC'],
    status: 'PUBLISHED',
    publishedAt: new Date().toISOString(),
    viewCount: 2310,
    clickCount: 620,
    applicantsCount: 620,
  },
  {
    _id: 'microsoft-devops-2026',
    title: 'Cloud Solutions & DevOps Engineer',
    slug: 'microsoft-cloud-devops-2026',
    companyName: 'Microsoft',
    jobType: 'FULL_TIME',
    location: 'Hyderabad / Noida / Remote',
    workMode: 'HYBRID',
    salaryOrStipend: '₹14 - 20 LPA',
    salaryRange: '₹14 - 20 LPA',
    batchEligible: ['2024', '2025', '2026'],
    eligibility: 'Engineering Graduates with strong Cloud & Networking foundation',
    applicationDeadline: '2026-12-15',
    deadline: '2026-12-15',
    applyUrl: 'https://careers.microsoft.com',
    whatsappCommunityUrl: 'https://whatsapp.com/channel/0029VbDKVvNHrDZgmPJIav3O',
    description: 'Build automated CI/CD pipelines, containerized Kubernetes microservices, and manage high-availability Azure cloud infrastructure.',
    requirements: [
      'Hands-on experience with Docker, Kubernetes, and Linux shell scripting',
      'Understanding of TCP/IP, DNS, VPC, load balancers, and network security',
      'Familiarity with Infrastructure as Code (Terraform) and Python scripting',
    ],
    selectionRounds: ['Online Assessment', 'Technical Round 1 (Cloud & Linux)', 'Technical Round 2 (Scripting)', 'Leadership Principles'],
    tags: ['Microsoft', 'Azure', 'DevOps', 'Kubernetes', 'Cloud'],
    status: 'PUBLISHED',
    publishedAt: new Date().toISOString(),
    viewCount: 1890,
    clickCount: 490,
    applicantsCount: 490,
  },
  {
    _id: 'tcs-digital-2026',
    title: 'Software Engineer - Campus Drive 2026',
    slug: 'tcs-digital-ninja-hiring-2026',
    companyName: 'TCS Digital & Prime',
    jobType: 'OFF_CAMPUS',
    location: 'Pan India',
    workMode: 'ON_SITE',
    salaryOrStipend: '₹7.2 - 9.0 LPA',
    salaryRange: '₹7.2 - 9.0 LPA',
    batchEligible: ['2025', '2026'],
    eligibility: 'All Engineering Branches (B.Tech / B.E.) with 60%+ in 10th, 12th & Degree',
    applicationDeadline: '2026-10-31',
    deadline: '2026-10-31',
    applyUrl: 'https://nextstep.tcs.com/campus/#/',
    whatsappCommunityUrl: 'https://whatsapp.com/channel/0029VbDKVvNHrDZgmPJIav3O',
    description: 'National Qualifier Test (TCS NQT) for Digital & Prime roles. Work on enterprise engineering, modern web applications, and AI analytics.',
    requirements: [
      'Proficiency in any one language: Python, Java, C++, or C#',
      'Aptitude, quantitative reasoning, and algorithmic problem solving',
    ],
    selectionRounds: ['TCS National Qualifier Test (NQT)', 'Technical & Coding Interview', 'HR Round'],
    tags: ['TCS', 'NQT', 'MassHiring', 'Freshers2026'],
    status: 'PUBLISHED',
    publishedAt: new Date().toISOString(),
    viewCount: 4200,
    clickCount: 1250,
    applicantsCount: 1250,
  },
];
